### ISSUE TITLE
newer release than 13.0.0

### ISSUE THREAD

**Issue by elgalu** [conda-forge/arrow-cpp-feedstock#1531]
### Comment:

I can only find version 13 in conda-forge https://anaconda.org/conda-forge/arrow-cpp but 17 is latest  https://arrow.apache.org/install/

it would also be great to use https://github.com/conda-forge/arrow-cpp-feedstock/releases so one can subscribe to updates there

**Comment by raulcd** [comment]
arrow-cpp was deprecated and removed in favour of libarrow. https://github.com/conda-forge/arrow-cpp-feedstock?tab=readme-ov-file#current-release-info

We deliver several more granular libraries:
![image](https://github.com/user-attachments/assets/05a2ea3a-63b9-4856-8f09-d6ff41636231)

Depending on your usage you might require only libarrow or you might require libarrow + other components (libarrow-dataset, libparquet, etc). If you need all you can use libarrow-all

**Comment by amoeba** [comment]
@raulcd would it be possible to remove [arrow-cpp](https://anaconda.org/conda-forge/arrow-cpp) or make it more clear that it's deprecated in favor of another set of packages?

**Comment by raulcd** [comment]
@amoeba do you mean on conda forge?

**Comment by raulcd** [comment]
I have no idea. Maybe @h-vetinari ?

**Comment by h-vetinari** [comment]
No, unfortunately t's not possible to remove arrow-cpp. We don't remove package artefacts once published.

If you're talking about the _name_ of the feedstock, then we could create a new one, but at the cost of losing a lot of history and context, which isn't worth it (and straight up renaming is out of the question due to the number of bots involved and ending up in an inconsistent state if done manually instead of through automation).

We do have a recipe linter working on conda-forge feedstocks that will warn if any recipe is still using the old name, but we don't show anything to endusers. Perhaps that's possible with conda's "package notices" functionality, but I've never seen that in use anywhere ao far.

**Comment by amoeba** [comment]
Thanks @h-vetinari. My concern here is mainly about user experience. It looks to me like https://anaconda.org/search?q=arrow sorts by download count and it ranks arrow-cpp above libarrow at the moment but I assume that will change over time as libarrow continues to gain downloads. Even if we could update the description for the `arrow-cpp` package I think that would be an improvement.
