### ISSUE TITLE
Can the aws-sdk-cpp pin be loosened?

### ISSUE THREAD

**Issue by akrherz** [conda-forge/arrow-cpp-feedstock#867]
### Comment:

I've been struggling with conda-forge dependency issues and now believe to have isolated it to the pinning on `aws-sdk-cpp` within this repo.  Does this pin still need to exist with the current 6.0 branch version of 6.0.2, which should have [ARROW-15141]( https://issues.apache.org/jira/browse/ARROW-15141) fixed?

Thank you.

**Comment by h-vetinari** [comment]
Thanks for the report!

>  Does this pin still need to exist with the current 6.0 branch version of 6.0.2, which should have [ARROW-15141](https://issues.apache.org/jira/browse/ARROW-15141) fixed?

That issue was fixed precisely by adding the pin. The unsolved root source of the problem is: https://github.com/aws/aws-sdk-cpp/issues/1809

The way I understood @pitrou, this is a hard blocker for removing the pin, and I'll treat it as such. Unfortunately, that means the only possibilities you have is to either convince aws-sdk-cpp to fix that issue or other consuming packages to expand their supported range of aws-sdk-cpp.

**Comment by akrherz** [comment]
Thank you @h-vetinari, I see what you are saying and digging more I find awslabs/aws-c-io#515 merged and in a release, which references the sdk-cpp issue.  Hmmm.

**Comment by h-vetinari** [comment]
> Thank you @h-vetinari, I see what you are saying and digging more I find [awslabs/aws-c-io#515](https://github.com/awslabs/aws-c-io/pull/515) merged and in a release, which references the sdk-cpp issue. Hmmm.

Good digging. Fix is unconfirmed AFAIU, but more importantly, not [part](https://github.com/aws/aws-sdk-cpp/issues/1809#issuecomment-1289859795) of aws-sdk-cpp yet (which affects us less because we unbundle the dependencies; but it could mean that the sdk-code is not tested/compatible with newer aws-c-* deps). On top of that, the migration for the respective aws-c-io release is currently running into an unresolved [problem](https://github.com/conda-forge/aws-c-http-feedstock/pull/79).

**Comment by h-vetinari** [comment]
This was done in #875 🥳 

It's on an exploratory basis because we cannot test the previous failure (in absence of AWS infra); let's hope we don't have to revert it 🤞
