### ISSUE TITLE
Ubuntu: libarrow conda package fails to install on ecryptfs

### ISSUE THREAD

**Issue by crusaderky** [conda-forge/arrow-cpp-feedstock#935]
Ubuntu 22.04.1 x86-64
conda 22.9.0 (defaults channel)

My home directory was created on top of ecryptfs by the Ubuntu installer:

> $ mount | grep home
> /home/.ecryptfs/crusaderky/.Private on /home/crusaderky type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=0ee7f63b0c91f840,ecryptfs_sig=c7f3e46a3b8390b1,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)

Trying to install libarrow with conda fails with `[Errno 36] File name too long`:
> $ conda create -n test libarrow                                                                                                                             
> InvalidArchiveError("Error with archive /home/crusaderky/miniconda3/pkgs/libarrow-10.0.1-h86614e7_4_cpu.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 36] File name too long: '/home/crusaderky/miniconda3/pkgs/libarrow-10.0.1-h86614e7_4_cpu/share/gdb/auto-load/home/conda/feedstock_root/build_artifacts/apache-arrow_1673819166020/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol'")

Out of the hundreds of other packages that I'm installing, libarrow seems to be the only problematic one.

### Workaround
Move the conda root dir to ext4:
```bash
$ sudo mkdir /home/$USER-nocrypt
$ sudo chown $USER:users /home/$USER-nocrypt
$ mv /home/$USER/miniconda3 /home/$USER-nocrypt/
$ ln -s /home/$USER-nocrypt/miniconda3 /home/$USER/miniconda3
$ conda create -n test libarrow
```

**Comment by h-vetinari** [comment]
Thanks for the report. This seems to be an issue with [something](https://github.com/regro/libcfgraph/blob/master/artifacts/libarrow/conda-forge/linux-64/libarrow-10.0.1-h86614e7_4_cpu.json#L825) related to gdb not getting cleaned up / normalized correctly after the build process:
```
  [...]
  "lib/pkgconfig/plasma.pc",
  "share/arrow/gdb/gdb_arrow.py",
  "share/doc/arrow/README.md",
  "share/gdb/auto-load/[BUILD_ENV]/lib/libarrow.so.1000.1.0-gdb.py"
```

@conda-forge/gdb any experience with something like that?

**Comment by h-vetinari** [comment]
@conda-forge/conda-build 

Apparently gdb-integration for arrow (or generally?) [needs](https://github.com/apache/arrow/blob/master/docs/source/cpp/gdb.rst#manual-loading) to have the _path to the installed `.so` **as part of the path** to the gdb-wrapper_. This uses `CMAKE_INSTALL_FULL_LIBDIR` upstream, which obviously points to the host-env during the build process, not the final user environment.

I've now patched this out because I don't see a way to make this relocatable, but wanted to ask if there's maybe any way I'm not aware of to _change the path of a non-binary file_ during installation.

The main issue I see is that we cannot know the path to the final environment before it is created. I guess it would also be possible to have an activation script that generates a symlink...
